# Generated by Django 4.1.7 on 2023-03-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='quantity',
        ),
        migrations.AddField(
            model_name='techcard',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
