# Generated by Django 4.1.7 on 2023-03-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0002_remove_cake_quantity_techcard_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techcard',
            old_name='cake',
            new_name='model_cake',
        ),
        migrations.RenameField(
            model_name='techcard',
            old_name='product',
            new_name='model_product',
        ),
    ]
