# Generated by Django 4.1.7 on 2023-03-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0003_rename_cake_techcard_model_cake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techcard', to='cake_app.cake'),
        ),
    ]
