# Generated by Django 4.1.7 on 2023-04-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0005_cake_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcard',
            name='model_cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake_app.cake'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake_app.product'),
        ),
    ]
