# Generated by Django 4.1.7 on 2023-04-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0006_alter_techcard_model_cake_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'ordering': ['id'], 'verbose_name': 'Торт', 'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='techcard',
            options={'ordering': ['model_cake'], 'verbose_name': 'Тех-карта', 'verbose_name_plural': 'Тех-карты'},
        ),
        migrations.AddField(
            model_name='cake',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(max_length=50, verbose_name='торт'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='slug',
            field=models.SlugField(verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake_app.cake', verbose_name='модель торта'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake_app.product', verbose_name='модель продукта'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='quantity',
            field=models.FloatField(verbose_name='количество'),
        ),
    ]
