# Generated by Django 4.1.7 on 2023-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0007_alter_cake_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
