# Generated by Django 4.1.7 on 2023-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0008_alter_cake_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='продукт'),
        ),
    ]
