# Generated by Django 4.1.7 on 2023-04-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='торт'),
        ),
    ]
