# Generated by Django 4.1.7 on 2023-04-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0012_alter_cake_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='слаг'),
        ),
    ]
