# Generated by Django 4.1.7 on 2023-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0013_alter_cake_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.ImageField(default=123, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
