# Generated by Django 4.1.7 on 2023-04-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0014_alter_cake_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='type',
            field=models.CharField(choices=[('cake', 'торт'), ('pankake', 'пироженое')], default='торт', max_length=50),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techcards', to='cake_app.cake', verbose_name='модель торта'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techcards', to='cake_app.product', verbose_name='модель продукта'),
        ),
    ]
