# Generated by Django 4.1.7 on 2023-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0015_cake_type_alter_techcard_model_cake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='type',
            field=models.CharField(choices=[('1', 'торт'), ('2', 'пироженое')], default='торт', max_length=50),
        ),
    ]
