# Generated by Django 4.1.7 on 2023-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0016_alter_cake_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='type',
            field=models.CharField(choices=[('1', 'торт'), ('2', 'пироженое')], max_length=50, verbose_name='разновидность'),
        ),
    ]
