# Generated by Django 4.1.7 on 2023-06-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0017_alter_cake_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='type',
            field=models.CharField(choices=[('1', 'торт'), ('2', 'пироженое')], max_length=50, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techcards', to='cake_app.cake', verbose_name='торт'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techcards', to='cake_app.product', verbose_name='продукт'),
        ),
    ]
