# Generated by Django 4.1.7 on 2023-06-04 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0018_alter_cake_type_alter_techcard_model_cake_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techcard',
            name='model_product',
        ),
        migrations.RemoveField(
            model_name='techcard',
            name='quantity',
        ),
        migrations.AddField(
            model_name='techcard',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_cake',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake_app.cake'),
        ),
    ]
