# Generated by Django 4.1.7 on 2023-06-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0019_remove_techcard_model_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcard',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='model_cake',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake_app.cake', verbose_name='Торт'),
        ),
    ]
