# Generated by Django 4.1.7 on 2023-06-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0021_alter_techcard_model_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TechCard',
        ),
    ]
