# Generated by Django 4.1.7 on 2023-07-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0023_rename_data_cake_techcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='techcard',
            field=models.JSONField(blank=True, null=True, verbose_name='Техкарта'),
        ),
    ]
